## Quick start : Compare runs choose a model , and deploy it to REST API

in this quickstart you will:

- Run a hyperparameter sweep on a traning script
- Compare the results of the runs in the MLflow UI
- Choose the best run and register it as a model
- Deploy the model to REST API
- Build a container image for deployment to a cloud platform

hyperopt - library that support hyperparameter in ann

In [2]:
import keras
import tensorflow as tf
import numpy as np
import pandas as pd
from hyperopt import fmin, tpe, hp, Trials, STATUS_OK
import mlflow
from mlflow import log_metric, log_param, log_artifacts
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import mlflow
from mlflow.models import infer_signature

In [7]:
## load dataset
data = pd.read_csv('data\wine.csv',sep=';')

In [8]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [13]:
data.count()

fixed acidity           1599
volatile acidity        1599
citric acid             1599
residual sugar          1599
chlorides               1599
free sulfur dioxide     1599
total sulfur dioxide    1599
density                 1599
pH                      1599
sulphates               1599
alcohol                 1599
quality                 1599
dtype: int64

In [14]:
## split data into training validating and testing 
## quality - dependent variable need to be predicted
## rest of the columns are independent variables that are used to predict quality means they are input features
train,test=train_test_split(data,test_size=0.25,random_state=42)
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
582,11.7,0.490,0.49,2.2,0.083,5.0,15.0,1.00000,3.19,0.43,9.2,5
626,8.8,0.600,0.29,2.2,0.098,5.0,15.0,0.99880,3.36,0.49,9.1,5
1030,7.1,0.590,0.00,2.1,0.091,9.0,14.0,0.99488,3.42,0.55,11.5,7
620,8.3,0.540,0.24,3.4,0.076,16.0,112.0,0.99760,3.27,0.61,9.4,5
490,9.3,0.775,0.27,2.8,0.078,24.0,56.0,0.99840,3.31,0.67,10.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1130,9.1,0.600,0.00,1.9,0.058,5.0,10.0,0.99770,3.18,0.63,10.4,6
1294,8.2,0.635,0.10,2.1,0.073,25.0,60.0,0.99638,3.29,0.75,10.9,6
860,7.2,0.620,0.06,2.7,0.077,15.0,85.0,0.99746,3.51,0.54,9.5,5
1459,7.9,0.200,0.35,1.7,0.054,7.0,15.0,0.99458,3.32,0.80,11.9,7
1126,5.8,0.290,0.26,1.7,0.063,3.0,11.0,0.99150,3.39,0.54,13.5,6

In [16]:
# Train dataset
train_x = train.drop('quality', axis=1).to_numpy()
train_y = train['quality'].to_numpy().ravel()

# Test dataset
test_x = test.drop('quality', axis=1).to_numpy()
test_y = test['quality'].to_numpy().ravel()

# Split train into train & validation
train_x, valid_x, train_y, valid_y = train_test_split(
    train_x, train_y, test_size=0.20, random_state=42
)

# MLflow signature
signature = infer_signature(train_x, train_y)

In [17]:
np.mean(train_x,axis=0)

array([ 8.29781022,  0.53131387,  0.2712513 ,  2.52591241,  0.08946403,
       15.88008342, 47.07351408,  0.99671879,  3.30930136,  0.6632951 ,
       10.42846715])

In [ ]:
## ANN Model

def train_model(params,epochs,train_x,train_y,valid_x,valid_y):

    ## Define the model
    mean=np.mean(train_x,axis=0)
    var=np.var(train_x,axis=0)

    model=keras.Sequential( 
        [
            keras.Input([train_x.shape[1]]),
            keras.layers.Normalization(mean=mean,variance=var),
            keras.layers.Dense(64,activation='relu'),
            keras.layers.Dense(1)
        ]
    )

### Compile the model
model.compile(optimizer=keras.optimizers.SGD(
    learning_rate=params["lr"],momentum=params["momentum"]
    ),
    loss='mean_squared_error',
    metrics=[keras.metrics.RootMeanSquaredError()]


    )
    ## Train the Ann model with Lr and momentum parameters
    with mlflow.start_run(nested=True):
        model.fi

In [18]:
import numpy as np
import mlflow
import mlflow.tensorflow
from tensorflow import keras
from hyperopt import STATUS_OK


## ANN Model training function
def train_model(params, epochs, train_x, train_y, valid_x, valid_y, signature):

    # Compute normalization statistics
    mean = np.mean(train_x, axis=0)
    var = np.var(train_x, axis=0)

    # Define the ANN model
    model = keras.Sequential(
        [
            keras.Input(shape=(train_x.shape[1],)),
            keras.layers.Normalization(mean=mean, variance=var),
            keras.layers.Dense(64, activation="relu"),
            keras.layers.Dense(1)
        ]
    )

    # Compile the model
    model.compile(
        optimizer=keras.optimizers.SGD(
            learning_rate=params["lr"],
            momentum=params["momentum"]
        ),
        loss="mean_squared_error",
        metrics=[keras.metrics.RootMeanSquaredError()]
    )

    # Train the ANN model with MLflow tracking
    with mlflow.start_run(nested=True):

        # Log hyperparameters
        mlflow.log_param("learning_rate", params["lr"])
        mlflow.log_param("momentum", params["momentum"])
        mlflow.log_param("epochs", epochs)
        mlflow.log_param("batch_size", 64)

        # Train model
        model.fit(
            train_x,
            train_y,
            validation_data=(valid_x, valid_y),
            epochs=epochs,
            batch_size=64,
            verbose=1
        )

        # Evaluate the model
        eval_result = model.evaluate(valid_x, valid_y, batch_size=64, verbose=0)
        eval_rmse = eval_result[1]

        # Log metric
        mlflow.log_metric("rmse", eval_rmse)

        # Log the model
        mlflow.tensorflow.log_model(
            model,
            artifact_path="model",
            signature=signature
        )

    return {
        "loss": eval_rmse,
        "status": STATUS_OK,
        "model": model
    }

In [19]:
def objective(params):
    result = train_model(
        params,
        epochs=50,
        train_x=train_x,
        train_y=train_y,
        valid_x=valid_x,
        valid_y=valid_y,
        signature=signature
    )
    return result

In [20]:
space = {
    "lr" :hp.loguniform("lr", np.log(1e-5), np.log(1e-1)),
    "momentum": hp.uniform("momentum", 0.0, 0.1)
}

In [21]:
mlflow.set_experiment("DL-MLflow-Wine-Quality")
with mlflow.start_run():
    ## Conduct hyperparameter optimization
    trials = Trials()
    best = fmin(
        fn=objective,
        space=space,
        algo=tpe.suggest,
        max_evals=4,
        trials=trials
    )

    # Fetch the best model
    best_run = sorted(trials.results, key=lambda x: x['loss'])[0]

    # Log the best parameters, loss , model
    mlflow.log_param(best)
    mlflow.log_metric("eval_rmse", best_run['loss'])
    mlflow.tensorflow.log_model(best_run['model'], "model", signature=signature)

    # print best hyperparameters and corresponding loss
    print(f"Best Parameters: {best}")
    print(f"Best eval RMSE: {best_run['loss']}")

2025/12/31 12:31:21 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2025/12/31 12:31:21 INFO mlflow.store.db.utils: Updating database tables
2025/12/31 12:31:21 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2025/12/31 12:31:21 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2025/12/31 12:31:21 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2025/12/31 12:31:21 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2025/12/31 12:31:21 INFO mlflow.tracking.fluent: Experiment with name 'DL-MLflow-Wine-Quality' does not exist. Creating a new experiment.

Epoch 1/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 12s 859ms/step - loss: 38.3812 - root_mean_squared_error: 6.1953
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 9.5744 - root_mean_squared_error: 3.0943 - val_loss: 1.8006 - val_root_mean_squared_error: 1.3419

Epoch 2/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.6277 - root_mean_squared_error: 1.2758
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3461 - root_mean_squared_error: 1.1602 - val_loss: 1.2079 - val_root_mean_squared_error: 1.0991

Epoch 3/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.1547 - root_mean_squared_error: 1.0745
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9880 - root_mean_squared_error: 0.9940 - val_loss: 1.0114 - val_root_mean_squared_error: 1.0057

Epoch 4/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.1176 - root_mean_squared_error: 1.0572
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8342 - root_mean_squared_error: 0.9133 - val_loss: 0.9087 - val_root_mean_squared_error: 0.9533

Epoch 5/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.7022 - root_mean_squared_error: 0.8380
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7378 - root_mean_squared_error: 0.8589 - val_loss: 0.8266 - val_root_mean_squared_error: 0.9092

Epoch 6/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.6394 - root_mean_squared_error: 0.7996
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6672 - root_mean_squared_error: 0.8168 - val_loss: 0.7797 - val_root_mean_squared_error: 0.8830

Epoch 7/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.6249 - root_mean_squared_error: 0.7905
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6129 - root_mean_squared_error: 0.7829 - val_loss: 0.7502 - val_root_mean_squared_error: 0.8662

Epoch 8/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4795 - root_mean_squared_error: 0.6925
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5696 - root_mean_squared_error: 0.7547 - val_loss: 0.6970 - val_root_mean_squared_error: 0.8349

Epoch 9/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4642 - root_mean_squared_error: 0.6813
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5381 - root_mean_squared_error: 0.7335 - val_loss: 0.6632 - val_root_mean_squared_error: 0.8144

Epoch 10/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.4623 - root_mean_squared_error: 0.6799
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5098 - root_mean_squared_error: 0.7140 - val_loss: 0.6657 - val_root_mean_squared_error: 0.8159

Epoch 11/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.4422 - root_mean_squared_error: 0.6650
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4882 - root_mean_squared_error: 0.6987 - val_loss: 0.6350 - val_root_mean_squared_error: 0.7968

Epoch 12/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3358 - root_mean_squared_error: 0.5795
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4693 - root_mean_squared_error: 0.6850 - val_loss: 0.6264 - val_root_mean_squared_error: 0.7914

Epoch 13/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.5041 - root_mean_squared_error: 0.7100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4550 - root_mean_squared_error: 0.6745 - val_loss: 0.6044 - val_root_mean_squared_error: 0.7774

Epoch 14/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3915 - root_mean_squared_error: 0.6257
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4383 - root_mean_squared_error: 0.6621 - val_loss: 0.5865 - val_root_mean_squared_error: 0.7658

Epoch 15/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4510 - root_mean_squared_error: 0.6715
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4338 - root_mean_squared_error: 0.6586 - val_loss: 0.5830 - val_root_mean_squared_error: 0.7635

Epoch 16/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4938 - root_mean_squared_error: 0.7027
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4192 - root_mean_squared_error: 0.6475 - val_loss: 0.5672 - val_root_mean_squared_error: 0.7531

Epoch 17/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3776 - root_mean_squared_error: 0.6145
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4143 - root_mean_squared_error: 0.6436 - val_loss: 0.5780 - val_root_mean_squared_error: 0.7603

Epoch 18/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.4242 - root_mean_squared_error: 0.6513
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4067 - root_mean_squared_error: 0.6377 - val_loss: 0.5722 - val_root_mean_squared_error: 0.7564

Epoch 19/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.3144 - root_mean_squared_error: 0.5607
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4041 - root_mean_squared_error: 0.6357 - val_loss: 0.5714 - val_root_mean_squared_error: 0.7559

Epoch 20/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.4240 - root_mean_squared_error: 0.6512
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3949 - root_mean_squared_error: 0.6284 - val_loss: 0.5554 - val_root_mean_squared_error: 0.7452

Epoch 21/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.5751 - root_mean_squared_error: 0.7583
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3928 - root_mean_squared_error: 0.6268 - val_loss: 0.5625 - val_root_mean_squared_error: 0.7500

Epoch 22/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.5227 - root_mean_squared_error: 0.7229
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3885 - root_mean_squared_error: 0.6233 - val_loss: 0.5671 - val_root_mean_squared_error: 0.7531

Epoch 23/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3404 - root_mean_squared_error: 0.5834
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3859 - root_mean_squared_error: 0.6212 - val_loss: 0.5467 - val_root_mean_squared_error: 0.7394

Epoch 24/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4240 - root_mean_squared_error: 0.6511
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3811 - root_mean_squared_error: 0.6173 - val_loss: 0.5536 - val_root_mean_squared_error: 0.7440

Epoch 25/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.4308 - root_mean_squared_error: 0.6564
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3805 - root_mean_squared_error: 0.6168 - val_loss: 0.5524 - val_root_mean_squared_error: 0.7432

Epoch 26/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.2750 - root_mean_squared_error: 0.5244
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3798 - root_mean_squared_error: 0.6163 - val_loss: 0.5594 - val_root_mean_squared_error: 0.7479

Epoch 27/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.3321 - root_mean_squared_error: 0.5763
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3770 - root_mean_squared_error: 0.6140 - val_loss: 0.5468 - val_root_mean_squared_error: 0.7395

Epoch 28/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.2917 - root_mean_squared_error: 0.5400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3730 - root_mean_squared_error: 0.6107 - val_loss: 0.5626 - val_root_mean_squared_error: 0.7501

Epoch 29/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.4572 - root_mean_squared_error: 0.6761
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3720 - root_mean_squared_error: 0.6099 - val_loss: 0.5449 - val_root_mean_squared_error: 0.7382

Epoch 30/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.2762 - root_mean_squared_error: 0.5256
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3682 - root_mean_squared_error: 0.6068 - val_loss: 0.5569 - val_root_mean_squared_error: 0.7462

Epoch 31/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.4466 - root_mean_squared_error: 0.6683
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3645 - root_mean_squared_error: 0.6037 - val_loss: 0.5361 - val_root_mean_squared_error: 0.7322

Epoch 32/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.2958 - root_mean_squared_error: 0.5438
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3682 - root_mean_squared_error: 0.6068 - val_loss: 0.5572 - val_root_mean_squared_error: 0.7464

Epoch 33/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3789 - root_mean_squared_error: 0.6156
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3618 - root_mean_squared_error: 0.6015 - val_loss: 0.5378 - val_root_mean_squared_error: 0.7333

Epoch 34/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2809 - root_mean_squared_error: 0.5300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3610 - root_mean_squared_error: 0.6008 - val_loss: 0.5388 - val_root_mean_squared_error: 0.7340

Epoch 35/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3781 - root_mean_squared_error: 0.6149
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3581 - root_mean_squared_error: 0.5984 - val_loss: 0.5404 - val_root_mean_squared_error: 0.7351

Epoch 36/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3180 - root_mean_squared_error: 0.5639
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3601 - root_mean_squared_error: 0.6001 - val_loss: 0.5359 - val_root_mean_squared_error: 0.7320

Epoch 37/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3078 - root_mean_squared_error: 0.5548
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3549 - root_mean_squared_error: 0.5957 - val_loss: 0.5462 - val_root_mean_squared_error: 0.7390

Epoch 38/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.3876 - root_mean_squared_error: 0.6226
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3590 - root_mean_squared_error: 0.5992 - val_loss: 0.5352 - val_root_mean_squared_error: 0.7316

Epoch 39/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.2036 - root_mean_squared_error: 0.4512
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3508 - root_mean_squared_error: 0.5923 - val_loss: 0.5438 - val_root_mean_squared_error: 0.7374

Epoch 40/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3404 - root_mean_squared_error: 0.5834
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3537 - root_mean_squared_error: 0.5947 - val_loss: 0.5316 - val_root_mean_squared_error: 0.7291

Epoch 41/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3412 - root_mean_squared_error: 0.5841
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3520 - root_mean_squared_error: 0.5933 - val_loss: 0.5310 - val_root_mean_squared_error: 0.7287

Epoch 42/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3187 - root_mean_squared_error: 0.5645
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3496 - root_mean_squared_error: 0.5912 - val_loss: 0.5220 - val_root_mean_squared_error: 0.7225

Epoch 43/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3276 - root_mean_squared_error: 0.5723
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3444 - root_mean_squared_error: 0.5868 - val_loss: 0.5644 - val_root_mean_squared_error: 0.7513

Epoch 44/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.4430 - root_mean_squared_error: 0.6656
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3484 - root_mean_squared_error: 0.5903 - val_loss: 0.5181 - val_root_mean_squared_error: 0.7198

Epoch 45/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.4222 - root_mean_squared_error: 0.6497
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3480 - root_mean_squared_error: 0.5899 - val_loss: 0.5297 - val_root_mean_squared_error: 0.7278

Epoch 46/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.4329 - root_mean_squared_error: 0.6580
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3456 - root_mean_squared_error: 0.5879 - val_loss: 0.5375 - val_root_mean_squared_error: 0.7332

Epoch 47/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.2561 - root_mean_squared_error: 0.5060
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3424 - root_mean_squared_error: 0.5852 - val_loss: 0.5375 - val_root_mean_squared_error: 0.7331

Epoch 48/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.4030 - root_mean_squared_error: 0.6348
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3446 - root_mean_squared_error: 0.5870 - val_loss: 0.5249 - val_root_mean_squared_error: 0.7245

Epoch 49/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.4052 - root_mean_squared_error: 0.6366
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3423 - root_mean_squared_error: 0.5851 - val_loss: 0.5512 - val_root_mean_squared_error: 0.7425

Epoch 50/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2893 - root_mean_squared_error: 0.5379
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3423 - root_mean_squared_error: 0.5851 - val_loss: 0.5380 - val_root_mean_squared_error: 0.7335

  0%|          | 0/4 [00:06<?, ?trial/s, best loss=?]

2025/12/31 12:31:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Epoch 1/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 4s 328ms/step - loss: 30.9881 - root_mean_squared_error: 5.5667
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 29.9603 - root_mean_squared_error: 5.4736 - val_loss: 27.5955 - val_root_mean_squared_error: 5.2531

Epoch 2/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 28.9131 - root_mean_squared_error: 5.3771
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.9929 - root_mean_squared_error: 5.1955 - val_loss: 24.8740 - val_root_mean_squared_error: 4.9874

Epoch 3/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 26.5810 - root_mean_squared_error: 5.1557
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24.3130 - root_mean_squared_error: 4.9308 - val_loss: 22.4090 - val_root_mean_squared_error: 4.7338

Epoch 4/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 22.5515 - root_mean_squared_error: 4.7488
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.8835 - root_mean_squared_error: 4.6780 - val_loss: 20.1709 - val_root_mean_squared_error: 4.4912

Epoch 5/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 20.4588 - root_mean_squared_error: 4.5231
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.6798 - root_mean_squared_error: 4.4362 - val_loss: 18.1369 - val_root_mean_squared_error: 4.2587

Epoch 6/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 19.2283 - root_mean_squared_error: 4.3850
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.6818 - root_mean_squared_error: 4.2050 - val_loss: 16.2902 - val_root_mean_squared_error: 4.0361

Epoch 7/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 15.9851 - root_mean_squared_error: 3.9981
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.8695 - root_mean_squared_error: 3.9837 - val_loss: 14.6157 - val_root_mean_squared_error: 3.8231

Epoch 8/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 15.2423 - root_mean_squared_error: 3.9041
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.2307 - root_mean_squared_error: 3.7724 - val_loss: 13.1022 - val_root_mean_squared_error: 3.6197

Epoch 9/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 14.5393 - root_mean_squared_error: 3.8130
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.7525 - root_mean_squared_error: 3.5711 - val_loss: 11.7372 - val_root_mean_squared_error: 3.4260

Epoch 10/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 12.4440 - root_mean_squared_error: 3.5276
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.4232 - root_mean_squared_error: 3.3798 - val_loss: 10.5111 - val_root_mean_squared_error: 3.2421

Epoch 11/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 11.0120 - root_mean_squared_error: 3.3184
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.2330 - root_mean_squared_error: 3.1989 - val_loss: 9.4156 - val_root_mean_squared_error: 3.0685

Epoch 12/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 8.0345 - root_mean_squared_error: 2.8345
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.1732 - root_mean_squared_error: 3.0287 - val_loss: 8.4400 - val_root_mean_squared_error: 2.9052

Epoch 13/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 8.6806 - root_mean_squared_error: 2.9463
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2335 - root_mean_squared_error: 2.8694 - val_loss: 7.5770 - val_root_mean_squared_error: 2.7526

Epoch 14/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 7.0874 - root_mean_squared_error: 2.6622
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4036 - root_mean_squared_error: 2.7210 - val_loss: 6.8157 - val_root_mean_squared_error: 2.6107

Epoch 15/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 6.0557 - root_mean_squared_error: 2.4608
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.6735 - root_mean_squared_error: 2.5833 - val_loss: 6.1469 - val_root_mean_squared_error: 2.4793

Epoch 16/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.8758 - root_mean_squared_error: 2.4240
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0348 - root_mean_squared_error: 2.4566 - val_loss: 5.5639 - val_root_mean_squared_error: 2.3588

Epoch 17/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.2671 - root_mean_squared_error: 2.5034
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.4793 - root_mean_squared_error: 2.3408 - val_loss: 5.0563 - val_root_mean_squared_error: 2.2486

Epoch 18/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.6164 - root_mean_squared_error: 2.3699
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.9957 - root_mean_squared_error: 2.2351 - val_loss: 4.6154 - val_root_mean_squared_error: 2.1483

Epoch 19/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 5.5528 - root_mean_squared_error: 2.3564
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5763 - root_mean_squared_error: 2.1392 - val_loss: 4.2343 - val_root_mean_squared_error: 2.0577

Epoch 20/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 4.5857 - root_mean_squared_error: 2.1414
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.2146 - root_mean_squared_error: 2.0529 - val_loss: 3.9060 - val_root_mean_squared_error: 1.9764

Epoch 21/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3.3435 - root_mean_squared_error: 1.8285
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9026 - root_mean_squared_error: 1.9755 - val_loss: 3.6232 - val_root_mean_squared_error: 1.9035

Epoch 22/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 3.9811 - root_mean_squared_error: 1.9953
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6334 - root_mean_squared_error: 1.9062 - val_loss: 3.3798 - val_root_mean_squared_error: 1.8384

Epoch 23/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 3.6476 - root_mean_squared_error: 1.9099
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.4019 - root_mean_squared_error: 1.8444 - val_loss: 3.1704 - val_root_mean_squared_error: 1.7806

Epoch 24/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 3.0626 - root_mean_squared_error: 1.7500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.2028 - root_mean_squared_error: 1.7896 - val_loss: 2.9912 - val_root_mean_squared_error: 1.7295

Epoch 25/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 3.0979 - root_mean_squared_error: 1.7601
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.0315 - root_mean_squared_error: 1.7411 - val_loss: 2.8368 - val_root_mean_squared_error: 1.6843

Epoch 26/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.3445 - root_mean_squared_error: 1.5312
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8832 - root_mean_squared_error: 1.6980 - val_loss: 2.7035 - val_root_mean_squared_error: 1.6442

Epoch 27/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.2918 - root_mean_squared_error: 1.5139
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7551 - root_mean_squared_error: 1.6599 - val_loss: 2.5888 - val_root_mean_squared_error: 1.6090

Epoch 28/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.6554 - root_mean_squared_error: 1.6295
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6436 - root_mean_squared_error: 1.6259 - val_loss: 2.4892 - val_root_mean_squared_error: 1.5777

Epoch 29/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.5596 - root_mean_squared_error: 1.5999
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5464 - root_mean_squared_error: 1.5957 - val_loss: 2.4028 - val_root_mean_squared_error: 1.5501

Epoch 30/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.3775 - root_mean_squared_error: 1.5419
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.4617 - root_mean_squared_error: 1.5690 - val_loss: 2.3275 - val_root_mean_squared_error: 1.5256

Epoch 31/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.0462 - root_mean_squared_error: 1.4305
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.3874 - root_mean_squared_error: 1.5451 - val_loss: 2.2615 - val_root_mean_squared_error: 1.5038

Epoch 32/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 2.5961 - root_mean_squared_error: 1.6112
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.3215 - root_mean_squared_error: 1.5237 - val_loss: 2.2031 - val_root_mean_squared_error: 1.4843

Epoch 33/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.4914 - root_mean_squared_error: 1.5784
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.2628 - root_mean_squared_error: 1.5043 - val_loss: 2.1512 - val_root_mean_squared_error: 1.4667

Epoch 34/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.2449 - root_mean_squared_error: 1.4983
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.2098 - root_mean_squared_error: 1.4865 - val_loss: 2.1047 - val_root_mean_squared_error: 1.4508

Epoch 35/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.6736 - root_mean_squared_error: 1.6351
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.1626 - root_mean_squared_error: 1.4706 - val_loss: 2.0629 - val_root_mean_squared_error: 1.4363

Epoch 36/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.9372 - root_mean_squared_error: 1.3918
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.1195 - root_mean_squared_error: 1.4558 - val_loss: 2.0251 - val_root_mean_squared_error: 1.4231

Epoch 37/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.9719 - root_mean_squared_error: 1.4042
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.0800 - root_mean_squared_error: 1.4422 - val_loss: 1.9908 - val_root_mean_squared_error: 1.4109

Epoch 38/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.8379 - root_mean_squared_error: 1.3557
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.0437 - root_mean_squared_error: 1.4296 - val_loss: 1.9593 - val_root_mean_squared_error: 1.3997

Epoch 39/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.6451 - root_mean_squared_error: 1.2826
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.0104 - root_mean_squared_error: 1.4179 - val_loss: 1.9302 - val_root_mean_squared_error: 1.3893

Epoch 40/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.6826 - root_mean_squared_error: 1.6379
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9792 - root_mean_squared_error: 1.4068 - val_loss: 1.9031 - val_root_mean_squared_error: 1.3795

Epoch 41/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 2.1379 - root_mean_squared_error: 1.4621
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9505 - root_mean_squared_error: 1.3966 - val_loss: 1.8778 - val_root_mean_squared_error: 1.3703

Epoch 42/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.2922 - root_mean_squared_error: 1.5140
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9229 - root_mean_squared_error: 1.3867 - val_loss: 1.8540 - val_root_mean_squared_error: 1.3616

Epoch 43/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.7178 - root_mean_squared_error: 1.3107
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.8967 - root_mean_squared_error: 1.3772 - val_loss: 1.8316 - val_root_mean_squared_error: 1.3534

Epoch 44/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 2.0009 - root_mean_squared_error: 1.4145
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8723 - root_mean_squared_error: 1.3683 - val_loss: 1.8102 - val_root_mean_squared_error: 1.3455

Epoch 45/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.8696 - root_mean_squared_error: 1.3673
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8489 - root_mean_squared_error: 1.3597 - val_loss: 1.7900 - val_root_mean_squared_error: 1.3379

Epoch 46/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1.8537 - root_mean_squared_error: 1.3615
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8268 - root_mean_squared_error: 1.3516 - val_loss: 1.7706 - val_root_mean_squared_error: 1.3307

Epoch 47/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.7589 - root_mean_squared_error: 1.3263
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.8056 - root_mean_squared_error: 1.3437 - val_loss: 1.7522 - val_root_mean_squared_error: 1.3237

Epoch 48/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.8319 - root_mean_squared_error: 1.6828
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7853 - root_mean_squared_error: 1.3362 - val_loss: 1.7345 - val_root_mean_squared_error: 1.3170

Epoch 49/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.4291 - root_mean_squared_error: 1.1954
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7658 - root_mean_squared_error: 1.3289 - val_loss: 1.7176 - val_root_mean_squared_error: 1.3106

Epoch 50/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.5867 - root_mean_squared_error: 1.2597
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7469 - root_mean_squared_error: 1.3217 - val_loss: 1.7012 - val_root_mean_squared_error: 1.3043

 25%|██▌       | 1/4 [00:24<00:56, 18.74s/trial, best loss: 0.7334801554679871]

2025/12/31 12:31:47 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Epoch 1/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 4s 299ms/step - loss: 33.0326 - root_mean_squared_error: 5.7474
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32.8552 - root_mean_squared_error: 5.7319 - val_loss: 31.8483 - val_root_mean_squared_error: 5.6434

Epoch 2/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 33.2619 - root_mean_squared_error: 5.7673
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32.5323 - root_mean_squared_error: 5.7037 - val_loss: 31.5340 - val_root_mean_squared_error: 5.6155

Epoch 3/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 31.6090 - root_mean_squared_error: 5.6222
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32.2131 - root_mean_squared_error: 5.6757 - val_loss: 31.2234 - val_root_mean_squared_error: 5.5878

Epoch 4/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 31.1231 - root_mean_squared_error: 5.5788
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 31.8973 - root_mean_squared_error: 5.6478 - val_loss: 30.9160 - val_root_mean_squared_error: 5.5602

Epoch 5/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 31.1129 - root_mean_squared_error: 5.5779
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 31.5850 - root_mean_squared_error: 5.6201 - val_loss: 30.6120 - val_root_mean_squared_error: 5.5328

Epoch 6/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 32.4369 - root_mean_squared_error: 5.6953
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 31.2763 - root_mean_squared_error: 5.5925 - val_loss: 30.3115 - val_root_mean_squared_error: 5.5056

Epoch 7/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 27.3355 - root_mean_squared_error: 5.2283
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30.9708 - root_mean_squared_error: 5.5651 - val_loss: 30.0142 - val_root_mean_squared_error: 5.4785

Epoch 8/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 29.7732 - root_mean_squared_error: 5.4565
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 30.6686 - root_mean_squared_error: 5.5379 - val_loss: 29.7200 - val_root_mean_squared_error: 5.4516

Epoch 9/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 32.5721 - root_mean_squared_error: 5.7072
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30.3699 - root_mean_squared_error: 5.5109 - val_loss: 29.4290 - val_root_mean_squared_error: 5.4248

Epoch 10/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 31.7039 - root_mean_squared_error: 5.6306
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 30.0743 - root_mean_squared_error: 5.4840 - val_loss: 29.1411 - val_root_mean_squared_error: 5.3983

Epoch 11/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 30.8196 - root_mean_squared_error: 5.5515
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 29.7819 - root_mean_squared_error: 5.4573 - val_loss: 28.8563 - val_root_mean_squared_error: 5.3718

Epoch 12/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 29.9254 - root_mean_squared_error: 5.4704
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 29.4925 - root_mean_squared_error: 5.4307 - val_loss: 28.5745 - val_root_mean_squared_error: 5.3455

Epoch 13/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 29.4214 - root_mean_squared_error: 5.4241
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 29.2063 - root_mean_squared_error: 5.4043 - val_loss: 28.2958 - val_root_mean_squared_error: 5.3194

Epoch 14/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 29.8658 - root_mean_squared_error: 5.4650
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.9230 - root_mean_squared_error: 5.3780 - val_loss: 28.0198 - val_root_mean_squared_error: 5.2934

Epoch 15/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 27.5257 - root_mean_squared_error: 5.2465
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.6430 - root_mean_squared_error: 5.3519 - val_loss: 27.7468 - val_root_mean_squared_error: 5.2675

Epoch 16/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 29.3096 - root_mean_squared_error: 5.4138
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.3657 - root_mean_squared_error: 5.3259 - val_loss: 27.4767 - val_root_mean_squared_error: 5.2418

Epoch 17/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 28.9167 - root_mean_squared_error: 5.3774
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.0913 - root_mean_squared_error: 5.3001 - val_loss: 27.2092 - val_root_mean_squared_error: 5.2162

Epoch 18/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 28.1541 - root_mean_squared_error: 5.3060
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 27.8196 - root_mean_squared_error: 5.2744 - val_loss: 26.9444 - val_root_mean_squared_error: 5.1908

Epoch 19/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 28.3174 - root_mean_squared_error: 5.3214
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.5509 - root_mean_squared_error: 5.2489 - val_loss: 26.6823 - val_root_mean_squared_error: 5.1655

Epoch 20/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 28.1277 - root_mean_squared_error: 5.3036
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 27.2849 - root_mean_squared_error: 5.2235 - val_loss: 26.4229 - val_root_mean_squared_error: 5.1403

Epoch 21/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 30.3832 - root_mean_squared_error: 5.5121
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 27.0215 - root_mean_squared_error: 5.1982 - val_loss: 26.1661 - val_root_mean_squared_error: 5.1153

Epoch 22/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 26.7848 - root_mean_squared_error: 5.1754
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.7609 - root_mean_squared_error: 5.1731 - val_loss: 25.9120 - val_root_mean_squared_error: 5.0904

Epoch 23/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 24.5164 - root_mean_squared_error: 4.9514
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.5030 - root_mean_squared_error: 5.1481 - val_loss: 25.6602 - val_root_mean_squared_error: 5.0656

Epoch 24/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 26.1170 - root_mean_squared_error: 5.1105
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 26.2476 - root_mean_squared_error: 5.1232 - val_loss: 25.4111 - val_root_mean_squared_error: 5.0409

Epoch 25/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 25.2500 - root_mean_squared_error: 5.0249
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.9948 - root_mean_squared_error: 5.0985 - val_loss: 25.1644 - val_root_mean_squared_error: 5.0164

Epoch 26/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 28.3402 - root_mean_squared_error: 5.3236
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.7447 - root_mean_squared_error: 5.0739 - val_loss: 24.9203 - val_root_mean_squared_error: 4.9920

Epoch 27/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 27.6595 - root_mean_squared_error: 5.2592
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.4969 - root_mean_squared_error: 5.0494 - val_loss: 24.6786 - val_root_mean_squared_error: 4.9678

Epoch 28/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 27.6225 - root_mean_squared_error: 5.2557
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.2516 - root_mean_squared_error: 5.0251 - val_loss: 24.4392 - val_root_mean_squared_error: 4.9436

Epoch 29/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 27.4442 - root_mean_squared_error: 5.2387
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.0087 - root_mean_squared_error: 5.0009 - val_loss: 24.2022 - val_root_mean_squared_error: 4.9196

Epoch 30/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 25.2604 - root_mean_squared_error: 5.0260
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.7684 - root_mean_squared_error: 4.9768 - val_loss: 23.9675 - val_root_mean_squared_error: 4.8957

Epoch 31/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 23.8109 - root_mean_squared_error: 4.8796
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.5303 - root_mean_squared_error: 4.9528 - val_loss: 23.7352 - val_root_mean_squared_error: 4.8719

Epoch 32/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 24.1672 - root_mean_squared_error: 4.9160
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24.2945 - root_mean_squared_error: 4.9289 - val_loss: 23.5051 - val_root_mean_squared_error: 4.8482

Epoch 33/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 25.2621 - root_mean_squared_error: 5.0261
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24.0612 - root_mean_squared_error: 4.9052 - val_loss: 23.2773 - val_root_mean_squared_error: 4.8247

Epoch 34/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 24.1046 - root_mean_squared_error: 4.9096
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23.8300 - root_mean_squared_error: 4.8816 - val_loss: 23.0516 - val_root_mean_squared_error: 4.8012

Epoch 35/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 25.0075 - root_mean_squared_error: 5.0007
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23.6010 - root_mean_squared_error: 4.8581 - val_loss: 22.8282 - val_root_mean_squared_error: 4.7779

Epoch 36/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 23.3467 - root_mean_squared_error: 4.8318
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23.3745 - root_mean_squared_error: 4.8347 - val_loss: 22.6069 - val_root_mean_squared_error: 4.7547

Epoch 37/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 22.0451 - root_mean_squared_error: 4.6952
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23.1499 - root_mean_squared_error: 4.8114 - val_loss: 22.3878 - val_root_mean_squared_error: 4.7316

Epoch 38/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 22.2255 - root_mean_squared_error: 4.7144
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.9277 - root_mean_squared_error: 4.7883 - val_loss: 22.1709 - val_root_mean_squared_error: 4.7086

Epoch 39/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 23.1059 - root_mean_squared_error: 4.8069
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.7076 - root_mean_squared_error: 4.7653 - val_loss: 21.9560 - val_root_mean_squared_error: 4.6857

Epoch 40/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 23.3512 - root_mean_squared_error: 4.8323
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.4896 - root_mean_squared_error: 4.7423 - val_loss: 21.7432 - val_root_mean_squared_error: 4.6630

Epoch 41/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 23.8333 - root_mean_squared_error: 4.8819
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.2737 - root_mean_squared_error: 4.7195 - val_loss: 21.5323 - val_root_mean_squared_error: 4.6403

Epoch 42/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 23.0672 - root_mean_squared_error: 4.8028
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.0598 - root_mean_squared_error: 4.6968 - val_loss: 21.3236 - val_root_mean_squared_error: 4.6177

Epoch 43/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 20.7412 - root_mean_squared_error: 4.5542
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.8480 - root_mean_squared_error: 4.6742 - val_loss: 21.1168 - val_root_mean_squared_error: 4.5953

Epoch 44/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 22.2960 - root_mean_squared_error: 4.7219
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.6383 - root_mean_squared_error: 4.6517 - val_loss: 20.9120 - val_root_mean_squared_error: 4.5730

Epoch 45/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 20.5584 - root_mean_squared_error: 4.5341
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.4305 - root_mean_squared_error: 4.6293 - val_loss: 20.7091 - val_root_mean_squared_error: 4.5507

Epoch 46/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 22.3017 - root_mean_squared_error: 4.7225
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.2248 - root_mean_squared_error: 4.6070 - val_loss: 20.5080 - val_root_mean_squared_error: 4.5286

Epoch 47/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 21.4499 - root_mean_squared_error: 4.6314
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.0211 - root_mean_squared_error: 4.5849 - val_loss: 20.3089 - val_root_mean_squared_error: 4.5065

Epoch 48/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 20.0566 - root_mean_squared_error: 4.4785
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.8193 - root_mean_squared_error: 4.5628 - val_loss: 20.1118 - val_root_mean_squared_error: 4.4846

Epoch 49/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 21.2784 - root_mean_squared_error: 4.6129
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.6193 - root_mean_squared_error: 4.5409 - val_loss: 19.9164 - val_root_mean_squared_error: 4.4628

Epoch 50/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 21.9057 - root_mean_squared_error: 4.6804
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.4213 - root_mean_squared_error: 4.5190 - val_loss: 19.7230 - val_root_mean_squared_error: 4.4411

 50%|█████     | 2/4 [00:37<00:30, 15.44s/trial, best loss: 0.7334801554679871]

2025/12/31 12:32:00 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Epoch 1/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 4s 299ms/step - loss: 32.8911 - root_mean_squared_error: 5.7351
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.0543 - root_mean_squared_error: 2.6560 - val_loss: 1.5393 - val_root_mean_squared_error: 1.2407

Epoch 2/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.9683 - root_mean_squared_error: 1.4030
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3361 - root_mean_squared_error: 1.1559 - val_loss: 1.1464 - val_root_mean_squared_error: 1.0707

Epoch 3/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.9680 - root_mean_squared_error: 0.9839
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0404 - root_mean_squared_error: 1.0200 - val_loss: 0.9256 - val_root_mean_squared_error: 0.9621

Epoch 4/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.7149 - root_mean_squared_error: 0.8455
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8589 - root_mean_squared_error: 0.9268 - val_loss: 0.8457 - val_root_mean_squared_error: 0.9196

Epoch 5/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.8593 - root_mean_squared_error: 0.9270
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7411 - root_mean_squared_error: 0.8609 - val_loss: 0.7663 - val_root_mean_squared_error: 0.8754

Epoch 6/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8652 - root_mean_squared_error: 0.9301
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6656 - root_mean_squared_error: 0.8159 - val_loss: 0.7172 - val_root_mean_squared_error: 0.8469

Epoch 7/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7282 - root_mean_squared_error: 0.8533
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6086 - root_mean_squared_error: 0.7801 - val_loss: 0.6786 - val_root_mean_squared_error: 0.8237

Epoch 8/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7406 - root_mean_squared_error: 0.8606
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5551 - root_mean_squared_error: 0.7451 - val_loss: 0.6573 - val_root_mean_squared_error: 0.8108

Epoch 9/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.5515 - root_mean_squared_error: 0.7426
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5221 - root_mean_squared_error: 0.7226 - val_loss: 0.6313 - val_root_mean_squared_error: 0.7946

Epoch 10/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.4916 - root_mean_squared_error: 0.7011
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5005 - root_mean_squared_error: 0.7074 - val_loss: 0.5949 - val_root_mean_squared_error: 0.7713

Epoch 11/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4402 - root_mean_squared_error: 0.6635
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4775 - root_mean_squared_error: 0.6910 - val_loss: 0.5983 - val_root_mean_squared_error: 0.7735

Epoch 12/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.4940 - root_mean_squared_error: 0.7028
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4677 - root_mean_squared_error: 0.6839 - val_loss: 0.6012 - val_root_mean_squared_error: 0.7754

Epoch 13/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3877 - root_mean_squared_error: 0.6227
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4532 - root_mean_squared_error: 0.6732 - val_loss: 0.5893 - val_root_mean_squared_error: 0.7677

Epoch 14/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.5595 - root_mean_squared_error: 0.7480
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4416 - root_mean_squared_error: 0.6645 - val_loss: 0.5692 - val_root_mean_squared_error: 0.7545

Epoch 15/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.4729 - root_mean_squared_error: 0.6877
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4302 - root_mean_squared_error: 0.6559 - val_loss: 0.5473 - val_root_mean_squared_error: 0.7398

Epoch 16/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4069 - root_mean_squared_error: 0.6379
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4223 - root_mean_squared_error: 0.6499 - val_loss: 0.5323 - val_root_mean_squared_error: 0.7296

Epoch 17/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.2493 - root_mean_squared_error: 0.4993
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4154 - root_mean_squared_error: 0.6445 - val_loss: 0.5320 - val_root_mean_squared_error: 0.7294

Epoch 18/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.3447 - root_mean_squared_error: 0.5871
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4100 - root_mean_squared_error: 0.6403 - val_loss: 0.5781 - val_root_mean_squared_error: 0.7603

Epoch 19/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4115 - root_mean_squared_error: 0.6415
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4103 - root_mean_squared_error: 0.6406 - val_loss: 0.5351 - val_root_mean_squared_error: 0.7315

Epoch 20/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3931 - root_mean_squared_error: 0.6270
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4044 - root_mean_squared_error: 0.6359 - val_loss: 0.5569 - val_root_mean_squared_error: 0.7463

Epoch 21/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.5755 - root_mean_squared_error: 0.7586
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4044 - root_mean_squared_error: 0.6359 - val_loss: 0.5238 - val_root_mean_squared_error: 0.7237

Epoch 22/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3453 - root_mean_squared_error: 0.5876
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3970 - root_mean_squared_error: 0.6301 - val_loss: 0.5063 - val_root_mean_squared_error: 0.7116

Epoch 23/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.4094 - root_mean_squared_error: 0.6398
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3934 - root_mean_squared_error: 0.6272 - val_loss: 0.5384 - val_root_mean_squared_error: 0.7338

Epoch 24/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3573 - root_mean_squared_error: 0.5977
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3908 - root_mean_squared_error: 0.6251 - val_loss: 0.5192 - val_root_mean_squared_error: 0.7205

Epoch 25/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - loss: 0.4482 - root_mean_squared_error: 0.6695
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3886 - root_mean_squared_error: 0.6233 - val_loss: 0.5521 - val_root_mean_squared_error: 0.7430

Epoch 26/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.4979 - root_mean_squared_error: 0.7056
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3807 - root_mean_squared_error: 0.6170 - val_loss: 0.5067 - val_root_mean_squared_error: 0.7119

Epoch 27/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3763 - root_mean_squared_error: 0.6134
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3828 - root_mean_squared_error: 0.6187 - val_loss: 0.5003 - val_root_mean_squared_error: 0.7073

Epoch 28/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.3581 - root_mean_squared_error: 0.5984
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3824 - root_mean_squared_error: 0.6184 - val_loss: 0.4967 - val_root_mean_squared_error: 0.7048

Epoch 29/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.2548 - root_mean_squared_error: 0.5048
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3777 - root_mean_squared_error: 0.6146 - val_loss: 0.5418 - val_root_mean_squared_error: 0.7361

Epoch 30/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.5177 - root_mean_squared_error: 0.7195
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3732 - root_mean_squared_error: 0.6109 - val_loss: 0.5328 - val_root_mean_squared_error: 0.7299

Epoch 31/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.3576 - root_mean_squared_error: 0.5980
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3763 - root_mean_squared_error: 0.6134 - val_loss: 0.4974 - val_root_mean_squared_error: 0.7053

Epoch 32/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3555 - root_mean_squared_error: 0.5963
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3692 - root_mean_squared_error: 0.6076 - val_loss: 0.5155 - val_root_mean_squared_error: 0.7180

Epoch 33/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.4389 - root_mean_squared_error: 0.6625
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3678 - root_mean_squared_error: 0.6065 - val_loss: 0.5121 - val_root_mean_squared_error: 0.7156

Epoch 34/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3523 - root_mean_squared_error: 0.5936
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3734 - root_mean_squared_error: 0.6111 - val_loss: 0.5081 - val_root_mean_squared_error: 0.7128

Epoch 35/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3212 - root_mean_squared_error: 0.5667
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3690 - root_mean_squared_error: 0.6074 - val_loss: 0.5435 - val_root_mean_squared_error: 0.7372

Epoch 36/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.2758 - root_mean_squared_error: 0.5252
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3649 - root_mean_squared_error: 0.6041 - val_loss: 0.4936 - val_root_mean_squared_error: 0.7026

Epoch 37/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.3931 - root_mean_squared_error: 0.6269
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3646 - root_mean_squared_error: 0.6039 - val_loss: 0.5011 - val_root_mean_squared_error: 0.7079

Epoch 38/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3701 - root_mean_squared_error: 0.6084
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3624 - root_mean_squared_error: 0.6020 - val_loss: 0.4975 - val_root_mean_squared_error: 0.7053

Epoch 39/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3332 - root_mean_squared_error: 0.5773
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3629 - root_mean_squared_error: 0.6025 - val_loss: 0.4982 - val_root_mean_squared_error: 0.7058

Epoch 40/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.2141 - root_mean_squared_error: 0.4627
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3624 - root_mean_squared_error: 0.6020 - val_loss: 0.4859 - val_root_mean_squared_error: 0.6970

Epoch 41/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.3970 - root_mean_squared_error: 0.6301
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3630 - root_mean_squared_error: 0.6025 - val_loss: 0.4878 - val_root_mean_squared_error: 0.6984

Epoch 42/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3569 - root_mean_squared_error: 0.5974
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3629 - root_mean_squared_error: 0.6024 - val_loss: 0.4933 - val_root_mean_squared_error: 0.7024

Epoch 43/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.2854 - root_mean_squared_error: 0.5342
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3608 - root_mean_squared_error: 0.6007 - val_loss: 0.4931 - val_root_mean_squared_error: 0.7022

Epoch 44/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.4495 - root_mean_squared_error: 0.6705
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3568 - root_mean_squared_error: 0.5973 - val_loss: 0.4888 - val_root_mean_squared_error: 0.6991

Epoch 45/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.4455 - root_mean_squared_error: 0.6675
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3553 - root_mean_squared_error: 0.5961 - val_loss: 0.5080 - val_root_mean_squared_error: 0.7127

Epoch 46/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3663 - root_mean_squared_error: 0.6052
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3527 - root_mean_squared_error: 0.5939 - val_loss: 0.4838 - val_root_mean_squared_error: 0.6956

Epoch 47/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3770 - root_mean_squared_error: 0.6140
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3533 - root_mean_squared_error: 0.5944 - val_loss: 0.5039 - val_root_mean_squared_error: 0.7098

Epoch 48/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.3724 - root_mean_squared_error: 0.6102
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3528 - root_mean_squared_error: 0.5939 - val_loss: 0.4953 - val_root_mean_squared_error: 0.7038

Epoch 49/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 1s 75ms/step - loss: 0.2283 - root_mean_squared_error: 0.4778
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3516 - root_mean_squared_error: 0.5930 - val_loss: 0.4995 - val_root_mean_squared_error: 0.7068

Epoch 50/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4209 - root_mean_squared_error: 0.6487
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3534 - root_mean_squared_error: 0.5945 - val_loss: 0.5001 - val_root_mean_squared_error: 0.7072

 75%|███████▌  | 3/4 [00:50<00:14, 14.48s/trial, best loss: 0.7334801554679871]

2025/12/31 12:32:13 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

100%|██████████| 4/4 [00:58<00:00, 14.64s/trial, best loss: 0.7071940898895264]

TypeError: log_param() missing 1 required positional argument: 'value'

In [22]:
import mlflow
import mlflow.tensorflow
from hyperopt import Trials, fmin, tpe


# Set MLflow experiment
mlflow.set_experiment("DL-MLflow-Wine-Quality")

with mlflow.start_run():

    # Conduct hyperparameter optimization
    trials = Trials()

    best_params = fmin(
        fn=objective,
        space=space,
        algo=tpe.suggest,
        max_evals=4,
        trials=trials
    )

    # Get best trial based on minimum loss
    best_trial = sorted(trials.results, key=lambda x: x["loss"])[0]

    best_loss = best_trial["loss"]
    best_model = best_trial["model"]

    # Log best hyperparameters (individually)
    for param, value in best_params.items():
        mlflow.log_param(param, value)

    # Log best metric
    mlflow.log_metric("eval_rmse", best_loss)

    # Log best model
    mlflow.tensorflow.log_model(
        best_model,
        artifact_path="model",
        signature=signature
    )

    # Print results
    print(f"Best Parameters: {best_params}")
    print(f"Best eval RMSE: {best_loss}")

Epoch 1/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 4s 328ms/step - loss: 31.8135 - root_mean_squared_error: 5.6403
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 27.4867 - root_mean_squared_error: 5.2428 - val_loss: 22.7439 - val_root_mean_squared_error: 4.7691

Epoch 2/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 22.8145 - root_mean_squared_error: 4.7765
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.7697 - root_mean_squared_error: 4.6658 - val_loss: 17.9495 - val_root_mean_squared_error: 4.2367

Epoch 3/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 20.0142 - root_mean_squared_error: 4.4737
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.2866 - root_mean_squared_error: 4.1577 - val_loss: 14.1735 - val_root_mean_squared_error: 3.7648

Epoch 4/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 16.2665 - root_mean_squared_error: 4.0332
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.7536 - root_mean_squared_error: 3.7086 - val_loss: 11.2162 - val_root_mean_squared_error: 3.3491

Epoch 5/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 12.6576 - root_mean_squared_error: 3.5577
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.9831 - root_mean_squared_error: 3.3141 - val_loss: 8.9208 - val_root_mean_squared_error: 2.9868

Epoch 6/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 9.6523 - root_mean_squared_error: 3.1068
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.8303 - root_mean_squared_error: 2.9716 - val_loss: 7.1706 - val_root_mean_squared_error: 2.6778

Epoch 7/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 7.3154 - root_mean_squared_error: 2.7047
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.1784 - root_mean_squared_error: 2.6793 - val_loss: 5.8495 - val_root_mean_squared_error: 2.4186

Epoch 8/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 7.6262 - root_mean_squared_error: 2.7615
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9238 - root_mean_squared_error: 2.4339 - val_loss: 4.8709 - val_root_mean_squared_error: 2.2070

Epoch 9/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 5.9958 - root_mean_squared_error: 2.4486
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.9806 - root_mean_squared_error: 2.2317 - val_loss: 4.1486 - val_root_mean_squared_error: 2.0368

Epoch 10/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 4.5199 - root_mean_squared_error: 2.1260
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.2733 - root_mean_squared_error: 2.0672 - val_loss: 3.6192 - val_root_mean_squared_error: 1.9024

Epoch 11/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 3.1619 - root_mean_squared_error: 1.7782
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7430 - root_mean_squared_error: 1.9347 - val_loss: 3.2291 - val_root_mean_squared_error: 1.7970

Epoch 12/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 3.6424 - root_mean_squared_error: 1.9085
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3430 - root_mean_squared_error: 1.8284 - val_loss: 2.9391 - val_root_mean_squared_error: 1.7144

Epoch 13/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 3.5693 - root_mean_squared_error: 1.8893
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.0379 - root_mean_squared_error: 1.7430 - val_loss: 2.7207 - val_root_mean_squared_error: 1.6494

Epoch 14/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 3.1112 - root_mean_squared_error: 1.7639
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8044 - root_mean_squared_error: 1.6746 - val_loss: 2.5513 - val_root_mean_squared_error: 1.5973

Epoch 15/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.8616 - root_mean_squared_error: 1.6916
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6181 - root_mean_squared_error: 1.6181 - val_loss: 2.4151 - val_root_mean_squared_error: 1.5541

Epoch 16/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.8907 - root_mean_squared_error: 1.7002
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.4656 - root_mean_squared_error: 1.5702 - val_loss: 2.3034 - val_root_mean_squared_error: 1.5177

Epoch 17/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2.9072 - root_mean_squared_error: 1.7051
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.3399 - root_mean_squared_error: 1.5297 - val_loss: 2.2092 - val_root_mean_squared_error: 1.4864

Epoch 18/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 2.4845 - root_mean_squared_error: 1.5762
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.2343 - root_mean_squared_error: 1.4948 - val_loss: 2.1273 - val_root_mean_squared_error: 1.4585

Epoch 19/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.3291 - root_mean_squared_error: 1.5261
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.1424 - root_mean_squared_error: 1.4637 - val_loss: 2.0544 - val_root_mean_squared_error: 1.4333

Epoch 20/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.9908 - root_mean_squared_error: 1.4110
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.0621 - root_mean_squared_error: 1.4360 - val_loss: 1.9891 - val_root_mean_squared_error: 1.4104

Epoch 21/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.8475 - root_mean_squared_error: 1.3592
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.9906 - root_mean_squared_error: 1.4109 - val_loss: 1.9293 - val_root_mean_squared_error: 1.3890

Epoch 22/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1.3679 - root_mean_squared_error: 1.1696
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9266 - root_mean_squared_error: 1.3880 - val_loss: 1.8746 - val_root_mean_squared_error: 1.3692

Epoch 23/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.0241 - root_mean_squared_error: 1.4227
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8688 - root_mean_squared_error: 1.3670 - val_loss: 1.8240 - val_root_mean_squared_error: 1.3505

Epoch 24/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.8094 - root_mean_squared_error: 1.3451
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.8169 - root_mean_squared_error: 1.3479 - val_loss: 1.7769 - val_root_mean_squared_error: 1.3330

Epoch 25/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 2.4715 - root_mean_squared_error: 1.5721
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7692 - root_mean_squared_error: 1.3301 - val_loss: 1.7327 - val_root_mean_squared_error: 1.3163

Epoch 26/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.9872 - root_mean_squared_error: 1.4097
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7246 - root_mean_squared_error: 1.3132 - val_loss: 1.6912 - val_root_mean_squared_error: 1.3005

Epoch 27/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.0441 - root_mean_squared_error: 1.0218
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.6842 - root_mean_squared_error: 1.2978 - val_loss: 1.6525 - val_root_mean_squared_error: 1.2855

Epoch 28/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.7758 - root_mean_squared_error: 1.3326
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.6461 - root_mean_squared_error: 1.2830 - val_loss: 1.6162 - val_root_mean_squared_error: 1.2713

Epoch 29/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.8050 - root_mean_squared_error: 1.3435
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.6111 - root_mean_squared_error: 1.2693 - val_loss: 1.5821 - val_root_mean_squared_error: 1.2578

Epoch 30/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.7174 - root_mean_squared_error: 1.3105
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5778 - root_mean_squared_error: 1.2561 - val_loss: 1.5502 - val_root_mean_squared_error: 1.2451

Epoch 31/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1.4552 - root_mean_squared_error: 1.2063
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5474 - root_mean_squared_error: 1.2440 - val_loss: 1.5202 - val_root_mean_squared_error: 1.2329

Epoch 32/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.6649 - root_mean_squared_error: 1.2903
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.5186 - root_mean_squared_error: 1.2323 - val_loss: 1.4917 - val_root_mean_squared_error: 1.2214

Epoch 33/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.2603 - root_mean_squared_error: 1.5034
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4924 - root_mean_squared_error: 1.2216 - val_loss: 1.4651 - val_root_mean_squared_error: 1.2104

Epoch 34/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.7883 - root_mean_squared_error: 1.3373
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.4659 - root_mean_squared_error: 1.2107 - val_loss: 1.4396 - val_root_mean_squared_error: 1.1998

Epoch 35/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1.6391 - root_mean_squared_error: 1.2803
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.4423 - root_mean_squared_error: 1.2010 - val_loss: 1.4154 - val_root_mean_squared_error: 1.1897

Epoch 36/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.1883 - root_mean_squared_error: 1.0901
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.4190 - root_mean_squared_error: 1.1912 - val_loss: 1.3926 - val_root_mean_squared_error: 1.1801

Epoch 37/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.6365 - root_mean_squared_error: 1.2793
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3973 - root_mean_squared_error: 1.1821 - val_loss: 1.3711 - val_root_mean_squared_error: 1.1710

Epoch 38/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1.4639 - root_mean_squared_error: 1.2099
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3761 - root_mean_squared_error: 1.1731 - val_loss: 1.3507 - val_root_mean_squared_error: 1.1622

Epoch 39/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1.1771 - root_mean_squared_error: 1.0849
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3565 - root_mean_squared_error: 1.1647 - val_loss: 1.3312 - val_root_mean_squared_error: 1.1538

Epoch 40/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 1.3529 - root_mean_squared_error: 1.1631
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3379 - root_mean_squared_error: 1.1567 - val_loss: 1.3129 - val_root_mean_squared_error: 1.1458

Epoch 41/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1.2267 - root_mean_squared_error: 1.1076
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3198 - root_mean_squared_error: 1.1488 - val_loss: 1.2953 - val_root_mean_squared_error: 1.1381

Epoch 42/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.5156 - root_mean_squared_error: 1.2311
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3030 - root_mean_squared_error: 1.1415 - val_loss: 1.2786 - val_root_mean_squared_error: 1.1308

Epoch 43/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.4491 - root_mean_squared_error: 1.2038
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2865 - root_mean_squared_error: 1.1342 - val_loss: 1.2625 - val_root_mean_squared_error: 1.1236

Epoch 44/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.7226 - root_mean_squared_error: 1.3125
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2705 - root_mean_squared_error: 1.1271 - val_loss: 1.2467 - val_root_mean_squared_error: 1.1166

Epoch 45/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1.2269 - root_mean_squared_error: 1.1077
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2552 - root_mean_squared_error: 1.1204 - val_loss: 1.2320 - val_root_mean_squared_error: 1.1100

Epoch 46/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 1.5946 - root_mean_squared_error: 1.2628
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2404 - root_mean_squared_error: 1.1137 - val_loss: 1.2181 - val_root_mean_squared_error: 1.1037

Epoch 47/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.2491 - root_mean_squared_error: 1.1177
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2266 - root_mean_squared_error: 1.1075 - val_loss: 1.2046 - val_root_mean_squared_error: 1.0975

Epoch 48/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.0632 - root_mean_squared_error: 1.0311
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2131 - root_mean_squared_error: 1.1014 - val_loss: 1.1917 - val_root_mean_squared_error: 1.0916

Epoch 49/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.7730 - root_mean_squared_error: 1.3315
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2000 - root_mean_squared_error: 1.0955 - val_loss: 1.1791 - val_root_mean_squared_error: 1.0859

Epoch 50/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7171 - root_mean_squared_error: 0.8468
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.1872 - root_mean_squared_error: 1.0896 - val_loss: 1.1673 - val_root_mean_squared_error: 1.0804

  0%|          | 0/4 [00:05<?, ?trial/s, best loss=?]

2025/12/31 12:34:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Epoch 1/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 4s 315ms/step - loss: 37.3379 - root_mean_squared_error: 6.1105
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.2755 - root_mean_squared_error: 2.5051 - val_loss: 1.3630 - val_root_mean_squared_error: 1.1675

Epoch 2/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.6422 - root_mean_squared_error: 1.2815
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1494 - root_mean_squared_error: 1.0721 - val_loss: 1.0525 - val_root_mean_squared_error: 1.0259

Epoch 3/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.3580 - root_mean_squared_error: 1.1653
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8857 - root_mean_squared_error: 0.9411 - val_loss: 0.8735 - val_root_mean_squared_error: 0.9346

Epoch 4/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.0593 - root_mean_squared_error: 1.0292
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7331 - root_mean_squared_error: 0.8562 - val_loss: 0.8179 - val_root_mean_squared_error: 0.9044

Epoch 5/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4866 - root_mean_squared_error: 0.6976
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6557 - root_mean_squared_error: 0.8098 - val_loss: 0.7772 - val_root_mean_squared_error: 0.8816

Epoch 6/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.6285 - root_mean_squared_error: 0.7928
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5929 - root_mean_squared_error: 0.7700 - val_loss: 0.7391 - val_root_mean_squared_error: 0.8597

Epoch 7/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.5124 - root_mean_squared_error: 0.7159
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5482 - root_mean_squared_error: 0.7404 - val_loss: 0.6725 - val_root_mean_squared_error: 0.8200

Epoch 8/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4572 - root_mean_squared_error: 0.6761
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5203 - root_mean_squared_error: 0.7213 - val_loss: 0.6565 - val_root_mean_squared_error: 0.8103

Epoch 9/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.4222 - root_mean_squared_error: 0.6497
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4845 - root_mean_squared_error: 0.6961 - val_loss: 0.6451 - val_root_mean_squared_error: 0.8032

Epoch 10/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3557 - root_mean_squared_error: 0.5964
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4728 - root_mean_squared_error: 0.6876 - val_loss: 0.6331 - val_root_mean_squared_error: 0.7957

Epoch 11/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4802 - root_mean_squared_error: 0.6929
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4522 - root_mean_squared_error: 0.6725 - val_loss: 0.6017 - val_root_mean_squared_error: 0.7757

Epoch 12/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3329 - root_mean_squared_error: 0.5770
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4438 - root_mean_squared_error: 0.6662 - val_loss: 0.5859 - val_root_mean_squared_error: 0.7654

Epoch 13/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.5408 - root_mean_squared_error: 0.7354
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4320 - root_mean_squared_error: 0.6573 - val_loss: 0.6246 - val_root_mean_squared_error: 0.7903

Epoch 14/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3786 - root_mean_squared_error: 0.6153
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4204 - root_mean_squared_error: 0.6483 - val_loss: 0.5953 - val_root_mean_squared_error: 0.7716

Epoch 15/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3596 - root_mean_squared_error: 0.5997
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4267 - root_mean_squared_error: 0.6532 - val_loss: 0.5893 - val_root_mean_squared_error: 0.7676

Epoch 16/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.5736 - root_mean_squared_error: 0.7574
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4124 - root_mean_squared_error: 0.6422 - val_loss: 0.5763 - val_root_mean_squared_error: 0.7592

Epoch 17/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3489 - root_mean_squared_error: 0.5907
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4067 - root_mean_squared_error: 0.6377 - val_loss: 0.5560 - val_root_mean_squared_error: 0.7456

Epoch 18/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.3643 - root_mean_squared_error: 0.6036
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4015 - root_mean_squared_error: 0.6336 - val_loss: 0.5453 - val_root_mean_squared_error: 0.7385

Epoch 19/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4502 - root_mean_squared_error: 0.6710
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3916 - root_mean_squared_error: 0.6258 - val_loss: 0.5726 - val_root_mean_squared_error: 0.7567

Epoch 20/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.4250 - root_mean_squared_error: 0.6519
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3863 - root_mean_squared_error: 0.6215 - val_loss: 0.5453 - val_root_mean_squared_error: 0.7385

Epoch 21/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3439 - root_mean_squared_error: 0.5864
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3879 - root_mean_squared_error: 0.6228 - val_loss: 0.5369 - val_root_mean_squared_error: 0.7327

Epoch 22/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.2924 - root_mean_squared_error: 0.5408
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3806 - root_mean_squared_error: 0.6169 - val_loss: 0.5531 - val_root_mean_squared_error: 0.7437

Epoch 23/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.3196 - root_mean_squared_error: 0.5654
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3845 - root_mean_squared_error: 0.6201 - val_loss: 0.5331 - val_root_mean_squared_error: 0.7301

Epoch 24/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3605 - root_mean_squared_error: 0.6004
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3786 - root_mean_squared_error: 0.6153 - val_loss: 0.5267 - val_root_mean_squared_error: 0.7258

Epoch 25/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.2962 - root_mean_squared_error: 0.5442
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3701 - root_mean_squared_error: 0.6084 - val_loss: 0.5227 - val_root_mean_squared_error: 0.7230

Epoch 26/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3622 - root_mean_squared_error: 0.6019
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3669 - root_mean_squared_error: 0.6057 - val_loss: 0.5180 - val_root_mean_squared_error: 0.7197

Epoch 27/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3316 - root_mean_squared_error: 0.5759
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3707 - root_mean_squared_error: 0.6088 - val_loss: 0.5355 - val_root_mean_squared_error: 0.7318

Epoch 28/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3512 - root_mean_squared_error: 0.5926
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3655 - root_mean_squared_error: 0.6045 - val_loss: 0.5280 - val_root_mean_squared_error: 0.7267

Epoch 29/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3204 - root_mean_squared_error: 0.5661
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3724 - root_mean_squared_error: 0.6103 - val_loss: 0.5103 - val_root_mean_squared_error: 0.7143

Epoch 30/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.4752 - root_mean_squared_error: 0.6893
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3655 - root_mean_squared_error: 0.6046 - val_loss: 0.5291 - val_root_mean_squared_error: 0.7274

Epoch 31/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.3943 - root_mean_squared_error: 0.6279
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3655 - root_mean_squared_error: 0.6046 - val_loss: 0.5118 - val_root_mean_squared_error: 0.7154

Epoch 32/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.3877 - root_mean_squared_error: 0.6227
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3653 - root_mean_squared_error: 0.6044 - val_loss: 0.5113 - val_root_mean_squared_error: 0.7151

Epoch 33/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.4049 - root_mean_squared_error: 0.6363
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3604 - root_mean_squared_error: 0.6004 - val_loss: 0.5192 - val_root_mean_squared_error: 0.7205

Epoch 34/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2843 - root_mean_squared_error: 0.5332
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3565 - root_mean_squared_error: 0.5971 - val_loss: 0.5084 - val_root_mean_squared_error: 0.7130

Epoch 35/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2979 - root_mean_squared_error: 0.5458
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3529 - root_mean_squared_error: 0.5940 - val_loss: 0.5018 - val_root_mean_squared_error: 0.7084

Epoch 36/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.2280 - root_mean_squared_error: 0.4775
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3466 - root_mean_squared_error: 0.5887 - val_loss: 0.4989 - val_root_mean_squared_error: 0.7063

Epoch 37/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.2361 - root_mean_squared_error: 0.4859
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3480 - root_mean_squared_error: 0.5899 - val_loss: 0.5106 - val_root_mean_squared_error: 0.7146

Epoch 38/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4005 - root_mean_squared_error: 0.6329
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3481 - root_mean_squared_error: 0.5900 - val_loss: 0.5216 - val_root_mean_squared_error: 0.7222

Epoch 39/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.2834 - root_mean_squared_error: 0.5323
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3539 - root_mean_squared_error: 0.5949 - val_loss: 0.5228 - val_root_mean_squared_error: 0.7231

Epoch 40/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3326 - root_mean_squared_error: 0.5767
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3506 - root_mean_squared_error: 0.5921 - val_loss: 0.4951 - val_root_mean_squared_error: 0.7036

Epoch 41/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3305 - root_mean_squared_error: 0.5749
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3473 - root_mean_squared_error: 0.5894 - val_loss: 0.5474 - val_root_mean_squared_error: 0.7399

Epoch 42/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3473 - root_mean_squared_error: 0.5893
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3457 - root_mean_squared_error: 0.5880 - val_loss: 0.5326 - val_root_mean_squared_error: 0.7298

Epoch 43/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3012 - root_mean_squared_error: 0.5488
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3471 - root_mean_squared_error: 0.5892 - val_loss: 0.5134 - val_root_mean_squared_error: 0.7165

Epoch 44/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.2525 - root_mean_squared_error: 0.5025
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3380 - root_mean_squared_error: 0.5814 - val_loss: 0.5467 - val_root_mean_squared_error: 0.7394

Epoch 45/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3988 - root_mean_squared_error: 0.6315
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3453 - root_mean_squared_error: 0.5876 - val_loss: 0.5139 - val_root_mean_squared_error: 0.7169

Epoch 46/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.2214 - root_mean_squared_error: 0.4705
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3377 - root_mean_squared_error: 0.5811 - val_loss: 0.5231 - val_root_mean_squared_error: 0.7232

Epoch 47/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3223 - root_mean_squared_error: 0.5677
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3363 - root_mean_squared_error: 0.5799 - val_loss: 0.4935 - val_root_mean_squared_error: 0.7025

Epoch 48/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.4036 - root_mean_squared_error: 0.6353
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3434 - root_mean_squared_error: 0.5860 - val_loss: 0.5173 - val_root_mean_squared_error: 0.7192

Epoch 49/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3327 - root_mean_squared_error: 0.5768
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3367 - root_mean_squared_error: 0.5802 - val_loss: 0.5549 - val_root_mean_squared_error: 0.7449

Epoch 50/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3178 - root_mean_squared_error: 0.5638
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3406 - root_mean_squared_error: 0.5836 - val_loss: 0.5086 - val_root_mean_squared_error: 0.7132

 25%|██▌       | 1/4 [00:19<00:40, 13.64s/trial, best loss: 1.080430507659912]

2025/12/31 12:34:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Epoch 1/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 4s 296ms/step - loss: 36.8884 - root_mean_squared_error: 6.0736
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 35.0216 - root_mean_squared_error: 5.9179 - val_loss: 30.6796 - val_root_mean_squared_error: 5.5389

Epoch 2/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 35.4658 - root_mean_squared_error: 5.9553
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 30.1325 - root_mean_squared_error: 5.4893 - val_loss: 26.4186 - val_root_mean_squared_error: 5.1399

Epoch 3/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 25.8062 - root_mean_squared_error: 5.0800
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25.9793 - root_mean_squared_error: 5.0970 - val_loss: 22.7661 - val_root_mean_squared_error: 4.7714

Epoch 4/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 21.1393 - root_mean_squared_error: 4.5977
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.4105 - root_mean_squared_error: 4.7340 - val_loss: 19.6066 - val_root_mean_squared_error: 4.4279

Epoch 5/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 21.4815 - root_mean_squared_error: 4.6348
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.3204 - root_mean_squared_error: 4.3955 - val_loss: 16.8682 - val_root_mean_squared_error: 4.1071

Epoch 6/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 16.5490 - root_mean_squared_error: 4.0680
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16.6395 - root_mean_squared_error: 4.0792 - val_loss: 14.4898 - val_root_mean_squared_error: 3.8065

Epoch 7/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 14.9129 - root_mean_squared_error: 3.8617
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.3119 - root_mean_squared_error: 3.7831 - val_loss: 12.4309 - val_root_mean_squared_error: 3.5257

Epoch 8/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 13.4666 - root_mean_squared_error: 3.6697
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.2994 - root_mean_squared_error: 3.5070 - val_loss: 10.6553 - val_root_mean_squared_error: 3.2642

Epoch 9/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 11.3123 - root_mean_squared_error: 3.3634
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.5654 - root_mean_squared_error: 3.2505 - val_loss: 9.1342 - val_root_mean_squared_error: 3.0223

Epoch 10/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 9.9519 - root_mean_squared_error: 3.1547
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0808 - root_mean_squared_error: 3.0134 - val_loss: 7.8407 - val_root_mean_squared_error: 2.8001

Epoch 11/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 9.9576 - root_mean_squared_error: 3.1556
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8204 - root_mean_squared_error: 2.7965 - val_loss: 6.7495 - val_root_mean_squared_error: 2.5980

Epoch 12/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 6.8943 - root_mean_squared_error: 2.6257
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.7555 - root_mean_squared_error: 2.5991 - val_loss: 5.8345 - val_root_mean_squared_error: 2.4155

Epoch 13/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.6679 - root_mean_squared_error: 2.3807
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.8621 - root_mean_squared_error: 2.4212 - val_loss: 5.0757 - val_root_mean_squared_error: 2.2529

Epoch 14/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 4.7239 - root_mean_squared_error: 2.1735
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.1195 - root_mean_squared_error: 2.2626 - val_loss: 4.4493 - val_root_mean_squared_error: 2.1093

Epoch 15/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 4.6068 - root_mean_squared_error: 2.1464
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5033 - root_mean_squared_error: 2.1221 - val_loss: 3.9368 - val_root_mean_squared_error: 1.9841

Epoch 16/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 5.1159 - root_mean_squared_error: 2.2618
12/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3237 - root_mean_squared_error: 2.0781
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.9954 - root_mean_squared_error: 1.9988 - val_loss: 3.5177 - val_root_mean_squared_error: 1.8756

Epoch 17/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 3.5880 - root_mean_squared_error: 1.8942
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.5774 - root_mean_squared_error: 1.8914 - val_loss: 3.1774 - val_root_mean_squared_error: 1.7825

Epoch 18/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.7933 - root_mean_squared_error: 1.6713
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.2347 - root_mean_squared_error: 1.7985 - val_loss: 2.9010 - val_root_mean_squared_error: 1.7032

Epoch 19/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.4392 - root_mean_squared_error: 1.5618
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.9539 - root_mean_squared_error: 1.7187 - val_loss: 2.6777 - val_root_mean_squared_error: 1.6364

Epoch 20/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.7602 - root_mean_squared_error: 1.6614
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7243 - root_mean_squared_error: 1.6505 - val_loss: 2.4970 - val_root_mean_squared_error: 1.5802

Epoch 21/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3.4667 - root_mean_squared_error: 1.8619
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5355 - root_mean_squared_error: 1.5923 - val_loss: 2.3499 - val_root_mean_squared_error: 1.5330

Epoch 22/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.8893 - root_mean_squared_error: 1.6998
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.3798 - root_mean_squared_error: 1.5427 - val_loss: 2.2296 - val_root_mean_squared_error: 1.4932

Epoch 23/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.9176 - root_mean_squared_error: 1.3848
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.2511 - root_mean_squared_error: 1.5004 - val_loss: 2.1307 - val_root_mean_squared_error: 1.4597

Epoch 24/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.2494 - root_mean_squared_error: 1.4998
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.1436 - root_mean_squared_error: 1.4641 - val_loss: 2.0486 - val_root_mean_squared_error: 1.4313

Epoch 25/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.4921 - root_mean_squared_error: 1.5787
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.0527 - root_mean_squared_error: 1.4327 - val_loss: 1.9796 - val_root_mean_squared_error: 1.4070

Epoch 26/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.9956 - root_mean_squared_error: 1.4127
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9759 - root_mean_squared_error: 1.4057 - val_loss: 1.9209 - val_root_mean_squared_error: 1.3860

Epoch 27/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.8956 - root_mean_squared_error: 1.3768
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9099 - root_mean_squared_error: 1.3820 - val_loss: 1.8709 - val_root_mean_squared_error: 1.3678

Epoch 28/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.4062 - root_mean_squared_error: 1.5512
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.8533 - root_mean_squared_error: 1.3614 - val_loss: 1.8271 - val_root_mean_squared_error: 1.3517

Epoch 29/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 2.1917 - root_mean_squared_error: 1.4804
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8031 - root_mean_squared_error: 1.3428 - val_loss: 1.7885 - val_root_mean_squared_error: 1.3373

Epoch 30/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.6141 - root_mean_squared_error: 1.2705
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.7589 - root_mean_squared_error: 1.3262 - val_loss: 1.7544 - val_root_mean_squared_error: 1.3245

Epoch 31/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 2.8393 - root_mean_squared_error: 1.6850
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7200 - root_mean_squared_error: 1.3115 - val_loss: 1.7231 - val_root_mean_squared_error: 1.3127

Epoch 32/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.5012 - root_mean_squared_error: 1.2252
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.6843 - root_mean_squared_error: 1.2978 - val_loss: 1.6948 - val_root_mean_squared_error: 1.3018

Epoch 33/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 2.2972 - root_mean_squared_error: 1.5157
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.6524 - root_mean_squared_error: 1.2855 - val_loss: 1.6686 - val_root_mean_squared_error: 1.2917

Epoch 34/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.1394 - root_mean_squared_error: 1.0674
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.6221 - root_mean_squared_error: 1.2736 - val_loss: 1.6442 - val_root_mean_squared_error: 1.2823

Epoch 35/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.3827 - root_mean_squared_error: 1.1759
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5945 - root_mean_squared_error: 1.2627 - val_loss: 1.6214 - val_root_mean_squared_error: 1.2733

Epoch 36/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.4781 - root_mean_squared_error: 1.2158
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5689 - root_mean_squared_error: 1.2526 - val_loss: 1.6003 - val_root_mean_squared_error: 1.2650

Epoch 37/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.4791 - root_mean_squared_error: 1.2162
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5457 - root_mean_squared_error: 1.2433 - val_loss: 1.5805 - val_root_mean_squared_error: 1.2572

Epoch 38/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.8619 - root_mean_squared_error: 1.3645
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.5230 - root_mean_squared_error: 1.2341 - val_loss: 1.5618 - val_root_mean_squared_error: 1.2497

Epoch 39/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.5090 - root_mean_squared_error: 1.2284
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5022 - root_mean_squared_error: 1.2256 - val_loss: 1.5438 - val_root_mean_squared_error: 1.2425

Epoch 40/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.2159 - root_mean_squared_error: 1.1027
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.4820 - root_mean_squared_error: 1.2174 - val_loss: 1.5268 - val_root_mean_squared_error: 1.2356

Epoch 41/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.6501 - root_mean_squared_error: 1.2846
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.4634 - root_mean_squared_error: 1.2097 - val_loss: 1.5104 - val_root_mean_squared_error: 1.2290

Epoch 42/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.0508 - root_mean_squared_error: 1.4321
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4455 - root_mean_squared_error: 1.2023 - val_loss: 1.4948 - val_root_mean_squared_error: 1.2226

Epoch 43/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.3208 - root_mean_squared_error: 1.1493
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.4017 - root_mean_squared_error: 1.1837
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.4282 - root_mean_squared_error: 1.1951 - val_loss: 1.4797 - val_root_mean_squared_error: 1.2164

Epoch 44/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.5406 - root_mean_squared_error: 1.2412
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.4117 - root_mean_squared_error: 1.1881 - val_loss: 1.4653 - val_root_mean_squared_error: 1.2105

Epoch 45/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1.6451 - root_mean_squared_error: 1.2826
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3961 - root_mean_squared_error: 1.1815 - val_loss: 1.4512 - val_root_mean_squared_error: 1.2047

Epoch 46/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.2925 - root_mean_squared_error: 1.1369
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3810 - root_mean_squared_error: 1.1752 - val_loss: 1.4376 - val_root_mean_squared_error: 1.1990

Epoch 47/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.3949 - root_mean_squared_error: 1.1811
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3663 - root_mean_squared_error: 1.1689 - val_loss: 1.4248 - val_root_mean_squared_error: 1.1936

Epoch 48/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.2723 - root_mean_squared_error: 1.1280
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3521 - root_mean_squared_error: 1.1628 - val_loss: 1.4123 - val_root_mean_squared_error: 1.1884

Epoch 49/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2.0143 - root_mean_squared_error: 1.4192
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3389 - root_mean_squared_error: 1.1571 - val_loss: 1.4004 - val_root_mean_squared_error: 1.1834

Epoch 50/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.5738 - root_mean_squared_error: 1.2545
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3262 - root_mean_squared_error: 1.1516 - val_loss: 1.3888 - val_root_mean_squared_error: 1.1785

 50%|█████     | 2/4 [00:32<00:26, 13.33s/trial, best loss: 0.7131500840187073]

2025/12/31 12:34:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Epoch 1/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 4s 308ms/step - loss: 32.3181 - root_mean_squared_error: 5.6849
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.0157 - root_mean_squared_error: 2.0039 - val_loss: 1.0423 - val_root_mean_squared_error: 1.0210

Epoch 2/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1.1895 - root_mean_squared_error: 1.0906
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8624 - root_mean_squared_error: 0.9286 - val_loss: 0.8460 - val_root_mean_squared_error: 0.9198

Epoch 3/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7297 - root_mean_squared_error: 0.8542
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6863 - root_mean_squared_error: 0.8284 - val_loss: 0.6971 - val_root_mean_squared_error: 0.8349

Epoch 4/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7209 - root_mean_squared_error: 0.8490
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5606 - root_mean_squared_error: 0.7487 - val_loss: 0.6759 - val_root_mean_squared_error: 0.8221

Epoch 5/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.5067 - root_mean_squared_error: 0.7119
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5616 - root_mean_squared_error: 0.7494 - val_loss: 0.6218 - val_root_mean_squared_error: 0.7885

Epoch 6/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4733 - root_mean_squared_error: 0.6879
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4695 - root_mean_squared_error: 0.6852 - val_loss: 0.5923 - val_root_mean_squared_error: 0.7696

Epoch 7/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.3593 - root_mean_squared_error: 0.5994
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4453 - root_mean_squared_error: 0.6673 - val_loss: 0.5574 - val_root_mean_squared_error: 0.7466

Epoch 8/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - loss: 0.4708 - root_mean_squared_error: 0.6862
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4438 - root_mean_squared_error: 0.6662 - val_loss: 0.5670 - val_root_mean_squared_error: 0.7530

Epoch 9/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4625 - root_mean_squared_error: 0.6801
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4198 - root_mean_squared_error: 0.6479 - val_loss: 0.5164 - val_root_mean_squared_error: 0.7186

Epoch 10/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4736 - root_mean_squared_error: 0.6882
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4321 - root_mean_squared_error: 0.6573 - val_loss: 0.5579 - val_root_mean_squared_error: 0.7469

Epoch 11/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.5026 - root_mean_squared_error: 0.7089
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4205 - root_mean_squared_error: 0.6485 - val_loss: 0.5519 - val_root_mean_squared_error: 0.7429

Epoch 12/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3605 - root_mean_squared_error: 0.6004
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4349 - root_mean_squared_error: 0.6594 - val_loss: 0.5647 - val_root_mean_squared_error: 0.7515

Epoch 13/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.6897 - root_mean_squared_error: 0.8305
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4246 - root_mean_squared_error: 0.6516 - val_loss: 0.5795 - val_root_mean_squared_error: 0.7612

Epoch 14/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.3849 - root_mean_squared_error: 0.6204
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4110 - root_mean_squared_error: 0.6411 - val_loss: 0.5389 - val_root_mean_squared_error: 0.7341

Epoch 15/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4287 - root_mean_squared_error: 0.6547
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3943 - root_mean_squared_error: 0.6280 - val_loss: 0.5544 - val_root_mean_squared_error: 0.7446

Epoch 16/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.4744 - root_mean_squared_error: 0.6887
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4023 - root_mean_squared_error: 0.6343 - val_loss: 0.5617 - val_root_mean_squared_error: 0.7494

Epoch 17/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.2785 - root_mean_squared_error: 0.5277
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4035 - root_mean_squared_error: 0.6352 - val_loss: 0.6555 - val_root_mean_squared_error: 0.8096

Epoch 18/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.4065 - root_mean_squared_error: 0.6376
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4077 - root_mean_squared_error: 0.6385 - val_loss: 0.5154 - val_root_mean_squared_error: 0.7179

Epoch 19/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3788 - root_mean_squared_error: 0.6155
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3795 - root_mean_squared_error: 0.6161 - val_loss: 0.5369 - val_root_mean_squared_error: 0.7327

Epoch 20/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3471 - root_mean_squared_error: 0.5892
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3892 - root_mean_squared_error: 0.6238 - val_loss: 0.6461 - val_root_mean_squared_error: 0.8038

Epoch 21/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.4002 - root_mean_squared_error: 0.6326
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4029 - root_mean_squared_error: 0.6347 - val_loss: 0.5293 - val_root_mean_squared_error: 0.7275

Epoch 22/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.2962 - root_mean_squared_error: 0.5443
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3654 - root_mean_squared_error: 0.6045 - val_loss: 0.5694 - val_root_mean_squared_error: 0.7546

Epoch 23/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4359 - root_mean_squared_error: 0.6602
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3832 - root_mean_squared_error: 0.6190 - val_loss: 0.5752 - val_root_mean_squared_error: 0.7584

Epoch 24/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.2688 - root_mean_squared_error: 0.5185
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3757 - root_mean_squared_error: 0.6130 - val_loss: 0.6128 - val_root_mean_squared_error: 0.7828

Epoch 25/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4442 - root_mean_squared_error: 0.6665
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3783 - root_mean_squared_error: 0.6151 - val_loss: 0.5704 - val_root_mean_squared_error: 0.7552

Epoch 26/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3686 - root_mean_squared_error: 0.6071
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3689 - root_mean_squared_error: 0.6074 - val_loss: 0.5614 - val_root_mean_squared_error: 0.7493

Epoch 27/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4037 - root_mean_squared_error: 0.6354
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3648 - root_mean_squared_error: 0.6040 - val_loss: 0.5393 - val_root_mean_squared_error: 0.7344

Epoch 28/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3056 - root_mean_squared_error: 0.5528
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3682 - root_mean_squared_error: 0.6068 - val_loss: 0.5319 - val_root_mean_squared_error: 0.7293

Epoch 29/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.4386 - root_mean_squared_error: 0.6623
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3625 - root_mean_squared_error: 0.6021 - val_loss: 0.5215 - val_root_mean_squared_error: 0.7221

Epoch 30/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3903 - root_mean_squared_error: 0.6248
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3885 - root_mean_squared_error: 0.6233 - val_loss: 0.5124 - val_root_mean_squared_error: 0.7158

Epoch 31/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3974 - root_mean_squared_error: 0.6304
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3524 - root_mean_squared_error: 0.5936 - val_loss: 0.5287 - val_root_mean_squared_error: 0.7271

Epoch 32/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4354 - root_mean_squared_error: 0.6598
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3609 - root_mean_squared_error: 0.6007 - val_loss: 0.5637 - val_root_mean_squared_error: 0.7508

Epoch 33/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3024 - root_mean_squared_error: 0.5500
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3613 - root_mean_squared_error: 0.6011 - val_loss: 0.5656 - val_root_mean_squared_error: 0.7521

Epoch 34/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2640 - root_mean_squared_error: 0.5138
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3996 - root_mean_squared_error: 0.6321 - val_loss: 0.5041 - val_root_mean_squared_error: 0.7100

Epoch 35/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3066 - root_mean_squared_error: 0.5537
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3485 - root_mean_squared_error: 0.5904 - val_loss: 0.5640 - val_root_mean_squared_error: 0.7510

Epoch 36/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.5018 - root_mean_squared_error: 0.7084
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3543 - root_mean_squared_error: 0.5952 - val_loss: 0.5743 - val_root_mean_squared_error: 0.7578

Epoch 37/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4283 - root_mean_squared_error: 0.6545
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3543 - root_mean_squared_error: 0.5952 - val_loss: 0.5371 - val_root_mean_squared_error: 0.7329

Epoch 38/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3925 - root_mean_squared_error: 0.6265
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3555 - root_mean_squared_error: 0.5962 - val_loss: 0.5583 - val_root_mean_squared_error: 0.7472

Epoch 39/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.4751 - root_mean_squared_error: 0.6893
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3510 - root_mean_squared_error: 0.5924 - val_loss: 0.5594 - val_root_mean_squared_error: 0.7479

Epoch 40/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.3347 - root_mean_squared_error: 0.5785
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3619 - root_mean_squared_error: 0.6016 - val_loss: 0.6235 - val_root_mean_squared_error: 0.7896

Epoch 41/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.3654 - root_mean_squared_error: 0.6045
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3445 - root_mean_squared_error: 0.5870 - val_loss: 0.5139 - val_root_mean_squared_error: 0.7169

Epoch 42/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3759 - root_mean_squared_error: 0.6131
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3633 - root_mean_squared_error: 0.6027 - val_loss: 0.5423 - val_root_mean_squared_error: 0.7364

Epoch 43/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.3572 - root_mean_squared_error: 0.5977
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3513 - root_mean_squared_error: 0.5927 - val_loss: 0.5260 - val_root_mean_squared_error: 0.7253

Epoch 44/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.2444 - root_mean_squared_error: 0.4944
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3392 - root_mean_squared_error: 0.5824 - val_loss: 0.5162 - val_root_mean_squared_error: 0.7185

Epoch 45/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.3583 - root_mean_squared_error: 0.5986
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3398 - root_mean_squared_error: 0.5829 - val_loss: 0.5653 - val_root_mean_squared_error: 0.7519

Epoch 46/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.2852 - root_mean_squared_error: 0.5340
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3369 - root_mean_squared_error: 0.5804 - val_loss: 0.5104 - val_root_mean_squared_error: 0.7145

Epoch 47/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3161 - root_mean_squared_error: 0.5622
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3302 - root_mean_squared_error: 0.5746 - val_loss: 0.5243 - val_root_mean_squared_error: 0.7241

Epoch 48/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3651 - root_mean_squared_error: 0.6042
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3327 - root_mean_squared_error: 0.5768 - val_loss: 0.5368 - val_root_mean_squared_error: 0.7326

Epoch 49/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2897 - root_mean_squared_error: 0.5382
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3503 - root_mean_squared_error: 0.5919 - val_loss: 0.5083 - val_root_mean_squared_error: 0.7129

Epoch 50/50

 1/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3335 - root_mean_squared_error: 0.5775
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3258 - root_mean_squared_error: 0.5708 - val_loss: 0.5139 - val_root_mean_squared_error: 0.7169

 75%|███████▌  | 3/4 [00:45<00:13, 13.24s/trial, best loss: 0.7131500840187073]

2025/12/31 12:35:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

100%|██████████| 4/4 [00:53<00:00, 13.42s/trial, best loss: 0.7131500840187073]

2025/12/31 12:35:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Best Parameters: {'lr': np.float64(0.030770641282547966), 'momentum': np.float64(0.0027617075273810524)}
Best eval RMSE: 0.7131500840187073

ravel - 1D array

##### train_x=train.drop('quality',axis=1).values() - exclude quality columns rest all in training set - group of independant variables

##### train_y=train['quality'].values.ravel() - only quality column - group of predict or depeandant column